dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'


networks:
  default: mainnet-fork
  goerli:
    weth_token: "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6"
    lending_pool_addresses: "0x5E52dEc931FFb32f609681B8438A51c675cc232d"
    verify: False
  mainnet-fork:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    lending_pool_addresses: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    verify: False
  development:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    lending_pool_addresses: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    verify: False
dotenv: .env
wallets:
  from_key: ${TESTNET_PRIVATE_KEY}